# Generated by Django 5.2.17 on 2026-09-30 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("short_description", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("composition", models.TextField(blank=True)),
                ("approved_benefits", models.TextField(blank=True)),
                ("approved_usage", models.TextField(blank=True)),
                ("precautions", models.TextField(blank=True)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("pack_size", models.CharField(blank=True, max_length=100)),
                ("mrp", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("gst_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["status"], name="products_pr_status_041708_idx"),
                    models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="products/%Y/%m/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video"), ("DOCUMENT", "Document")],
                        default="IMAGE",
                        max_length=16,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
    ]
