# Generated by Django 5.2.17 on 2026-09-30 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("META", "Meta"),
                            ("GOOGLE", "Google"),
                            ("INSTAGRAM", "Instagram"),
                            ("WHATSAPP", "WhatsApp"),
                            ("YOUTUBE", "YouTube"),
                            ("ORGANIC", "Organic"),
                            ("REFERRAL", "Referral"),
                            ("QR", "QR"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("campaign_code", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("PAUSED", "Paused"), ("ENDED", "Ended")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["campaign_code"], name="campaigns_c_campaig_e39038_idx")
                ],
            },
        ),
    ]
