# Generated by Django 5.2.17 on 2026-09-30 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lead_number", models.CharField(editable=False, max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=150, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "preferred_contact_method",
                    models.CharField(blank=True, default="PHONE", max_length=32),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=32)),
                ("medium", models.CharField(blank=True, max_length=64, null=True)),
                ("campaign_name", models.CharField(blank=True, max_length=255, null=True)),
                ("landing_page", models.URLField(blank=True, max_length=500, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=128, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=128, null=True)),
                ("utm_campaign", models.CharField(blank=True, max_length=128, null=True)),
                ("utm_term", models.CharField(blank=True, max_length=128, null=True)),
                ("utm_content", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("INTERESTED", "Interested"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("CONVERTED", "Converted"),
                            ("NOT_INTERESTED", "Not Interested"),
                            ("NO_RESPONSE", "No Response"),
                            ("INVALID", "Invalid"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("is_potential_duplicate", models.BooleanField(default=False)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeadStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_status", models.CharField(blank=True, max_length=32, null=True)),
                ("new_status", models.CharField(max_length=32)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="leads_lead_phone_709d42_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="leads_lead_status_e23abe_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["assigned_to"], name="leads_lead_assigne_3f8857_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["created_at"], name="leads_lead_created_302c6d_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["campaign"], name="leads_lead_campaig_7b0563_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["product"], name="leads_lead_product_ee019f_idx"),
        ),
    ]
