# Generated by Django 5.2.17 on 2026-09-30 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LAB_REPORT", "Lab report"),
                            ("SCAN", "Scan / imaging"),
                            ("PRESCRIPTION", "Prescription"),
                            ("DISCHARGE_SUMMARY", "Discharge summary"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=24,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clinical.patientprofile",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medicine", models.CharField(max_length=255)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                ("frequency", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("instructions", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_items",
                        to="clinical.consultation",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VitalReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField()),
                ("systolic_bp", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("diastolic_bp", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("heart_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "sleep_hours",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="clinical.patientprofile",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["patient", "recorded_at"], name="clinical_vi_patient_ad7d2a_idx"
                    )
                ],
            },
        ),
    ]
