# Generated by Django 5.2.17 on 2026-10-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_medicaldocument_prescriptionitem_vitalreading"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
