# Generated by Django 5.2.17 on 2026-10-01 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("MEDIANCE_GREEN", "Mediance Green"),
                            ("ROSE_PLUM", "Rose & Plum"),
                            ("LAVENDER_CALM", "Lavender Calm"),
                            ("PEACH_TEAL", "Peach & Teal"),
                            ("MAUVE_MINIMAL", "Mauve Minimal"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="MEDIANCE_GREEN",
                        max_length=32,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#0F9D78",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a 6-digit hex colour such as #D9467A."
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#7C5CF6",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a 6-digit hex colour such as #D9467A."
                            )
                        ],
                    ),
                ),
                (
                    "heading_font",
                    models.CharField(
                        choices=[
                            ("Plus Jakarta Sans", "Plus Jakarta Sans"),
                            ("Fraunces", "Fraunces"),
                            ("Quicksand", "Quicksand"),
                            ("DM Serif Display", "DM Serif Display"),
                            ("Playfair Display", "Playfair Display"),
                            ("Poppins", "Poppins"),
                        ],
                        default="Plus Jakarta Sans",
                        max_length=40,
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        choices=[
                            ("Plus Jakarta Sans", "Plus Jakarta Sans"),
                            ("Nunito", "Nunito"),
                            ("Poppins", "Poppins"),
                        ],
                        default="Plus Jakarta Sans",
                        max_length=40,
                    ),
                ),
                (
                    "corner_style",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("ROUND", "Extra round")],
                        default="STANDARD",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "site_theme",
            },
        ),
    ]
