# Generated by Django 5.2.17 on 2026-10-01 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to use the phone number on the account.",
                        max_length=20,
                    ),
                ),
                ("whatsapp_opt_in_at", models.DateTimeField(blank=True, null=True)),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contact_preferences",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome (new patient account)"),
                            ("ENQUIRY_RECEIVED", "Enquiry received"),
                            ("CONSULTATION_BOOKED", "Consultation booked / scheduled"),
                            ("CONSULTATION_REMINDER", "Consultation reminder"),
                            ("CONSULTATION_CANCELLED", "Consultation cancelled"),
                            ("PRESCRIPTION_READY", "Prescription ready"),
                            ("DOCUMENT_UPLOADED", "New report / document"),
                            ("DOCTOR_NEW_BOOKING", "Doctor: new booking"),
                            ("LEAD_ASSIGNED", "Sales: lead assigned"),
                            ("TEST", "Test message"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("WHATSAPP", "WhatsApp"), ("SMS", "SMS")],
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("whatsapp_template_name", models.CharField(blank=True, max_length=128)),
                ("whatsapp_params", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["event", "channel"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WELCOME", "Welcome (new patient account)"),
                    ("ENQUIRY_RECEIVED", "Enquiry received"),
                    ("CONSULTATION_BOOKED", "Consultation booked / scheduled"),
                    ("CONSULTATION_REMINDER", "Consultation reminder"),
                    ("CONSULTATION_CANCELLED", "Consultation cancelled"),
                    ("PRESCRIPTION_READY", "Prescription ready"),
                    ("DOCUMENT_UPLOADED", "New report / document"),
                    ("DOCTOR_NEW_BOOKING", "Doctor: new booking"),
                    ("LEAD_ASSIGNED", "Sales: lead assigned"),
                    ("TEST", "Test message"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="to_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["status", "channel"], name="notificatio_status_d69daf_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["event"], name="notificatio_event_518f73_idx"),
        ),
        migrations.AddField(
            model_name="contactpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="messagetemplate",
            constraint=models.UniqueConstraint(
                fields=("event", "channel"), name="unique_event_channel"
            ),
        ),
    ]
